export const INCREMENT_COUNTER = "INCREMENT_COUNTER"
export const DECREMENT_COUNTER = "DECREMENT_COUNTER"

export const GET_MEDICINES = "GET_MEDICINES"
export const ADD_MEDICINES = "ADD_MEDICINES"
export const LOADING_MEDICINES = "LOADING_MEDICINES"
export const ERROR_MEDICINES = "ERROR_MEDICINES"